[package]
name = "vocab-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
crossterm = "0.28.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "time"] }
async-trait = "0.1.83"
anyhow = "1.0.89"

ollama-rs = "0.2.1"
rand = "0.8.5"
